compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@storybook/core-common@7.4.5":
    dependencies:
      "@storybook/react-webpack5": 7.4.5
  "@types/react-router-dom@5.3.3":
    dependencies:
      react-router: 5.3.3
  croact-css-styled@1.1.9:
    dependencies:
      croact: 1.0.4
  doctrine@3.0.0:
    dependencies:
      assert: 2.0.0
  rc-time-picker@3.7.3:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1
  rc-trigger@2.6.5:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1
  react-compat-css-styled@1.0.8:
    dependencies:
      react-simple-compat: 1.2.2
  react-icons@2.2.7:
    peerDependencies:
      prop-types: "*"
  react-resizable@3.0.4:
    peerDependencies:
      react-dom: 17.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-4.0.2-git.20240118.hash-e135fc4.cjs
